//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogiApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> PhoneNumber { get; set; }
        public Nullable<int> OfficeNumber { get; set; }
        public Nullable<int> Fax { get; set; }
        public string Email { get; set; }
        public Nullable<int> ProviderID { get; set; }
    
        public virtual Provider Provider { get; set; }
    }
}
